export const LOGIN_START = 'LOGIN_START';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOAD_ARTICLE_START = "LOAD_ARTICLE_START";
export const LOAD_ARTICLE_DONE = "LOAD_ARTICLE_DONE";
export const LOAD_ARTICLE_FAILED = "LOAD_ARTICLE_FAILED";

export const SUBMIT_VOTE_START = "SUBMIT_VOTE_START";
export const SUBMIT_VOTE_DONE = "SUBMIT_VOTE_DONE";
