spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://dev.citizen.com.vn/oauth2/introspect
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/vote_db
    username: htadmin
    password: mysecretpassword
logging:
  level:
    root: DEBUG
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    com:
      example:
        demo:
          DEBUG